// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateInfo describes an available update. It is returned by [Updater.Check]
 * after manifest verification, semver comparison, and artefact matching.
 * The caller passes it to [Updater.Apply].
 */
export class UpdateInfo {
    "Version": string;
    "NotesURL": string;
    "URL": string;
    "SHA256": string;
    "Size": number;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }
        if (!("NotesURL" in $$source)) {
            this["NotesURL"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
