// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsApp is the bound service (v3) that was the bound struct (v2): the
 * frontend reaches the backend through these methods over the Wails runtime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

/**
 * ApplyUpdate applies a previously checked update. No arguments —
 * the update info is already verified and held in backend state.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.ApplyUpdate");
}

/**
 * CheckForUpdate fetches and verifies the signed release manifest.
 * Returns an update description if a newer version is available,
 * or null when already current or on a dev build.
 */
export function CheckForUpdate(): $CancellablePromise<update$0.UpdateInfo | null> {
    return $Call.ByName("main.WailsApp.CheckForUpdate").then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUpdateState returns the updater state for the UI notice.
 * "pending" means an update was applied and is waiting for a restart;
 * empty string means nothing in flight.
 */
export function GetUpdateState(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.GetUpdateState");
}

export function GetWSPort(): $CancellablePromise<number> {
    return $Call.ByName("main.WailsApp.GetWSPort");
}

export function GetWSToken(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.GetWSToken");
}

/**
 * Log logs a message from the frontend.
 */
export function Log(message: string): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.Log", message);
}

/**
 * LogFilePath reports where the backend log file lives, so a running
 * desktop session can say where its log is instead of it being guessed
 * from a file's mtime. "" means file logging is unavailable (stderr only).
 */
export function LogFilePath(): $CancellablePromise<string> {
    return $Call.ByName("main.WailsApp.LogFilePath");
}

/**
 * ReportHealthy signals that the frontend is running correctly.
 * Called once the initial tab's renderer mounted and its PTY session
 * opened (§7.5). Only then does the updater finalise a pending update.
 */
export function ReportHealthy(): $CancellablePromise<void> {
    return $Call.ByName("main.WailsApp.ReportHealthy");
}

// Private type creation functions
const $$createType0 = update$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
