// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<update.UpdateInfo>;

export function GetUpdateState():Promise<string>;

export function GetWSPort():Promise<number>;

export function GetWSToken():Promise<string>;

export function Log(arg1:string):Promise<void>;

export function LogFilePath():Promise<string>;

export function ReportHealthy():Promise<void>;
