// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['WailsApp']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['WailsApp']['CheckForUpdate']();
}

export function GetUpdateState() {
  return window['go']['main']['WailsApp']['GetUpdateState']();
}

export function GetWSPort() {
  return window['go']['main']['WailsApp']['GetWSPort']();
}

export function ReportHealthy() {
  return window['go']['main']['WailsApp']['ReportHealthy']();
}
